server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: '*'
#management:
#  health:
#    binders:
#      enabled: true
spring:
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        simple-message-in:
          group: consumer               # just a part of queue name(ending) subscribed to 'destination'
          destination: simple.message.in
        simple-message-out:
          destination: simple.message.out
        route-message-in:
          group: consumer
          destination: route.message.in
        unstable-message-in:
          group: consumer
          destination: unstable.message.in
          max-attempts: 1
          requeue-rejected: true
      rabbit:
        bindings:
          simple-message-out:
            producer:
              exchange-type: fanout
          route-message-in:
            consumer:
              bindingRoutingKey: "http://cft.ru/daily_news"
          unstable-message-in:
            consumer:
              #max-concurency: 1           # The maximum number of consumers. Not supported when the containerType is direct
              requeue-rejected: true
              bind-queue: true
              auto-bind-dlq: true
              dlq-ttl: 5000               # Default time to live to apply to the dead letter queue when declared (in milliseconds)
              dlq-dead-letter-exchange:

        binders:
          cluster_rabbit:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
                  virtual-host: /
